version: '3'

tasks:

  install:
    desc: "Install venv and pre-commit hooks"
    cmds:
      - echo "🚀 Creating virtual environment using uv"
      - uv sync
      - echo "🚀 Installing pre-commit hooks"
      - uv run pre-commit install

  check:
    desc: "Run different checks including linting"
    cmds:
      - echo "🚀 Checking lock file consistency with 'pyproject.toml'"
	    - uv lock --locked
	    - echo "🚀 Static type checking: Running mypy"
	    - uv run mypy
      - echo "🚀 Code formatting: Running black"
      - uv run black
      - echo "🚀 Linting: Running ruff"
      - uv run ruff

  test:
    desc: "Run tests"
    cmds:
      - echo "🚀 Running tests"
      - uv run python -m pytest --cov --cov-config=pyproject.toml tests
